// pages/admin/technology.tsx
import Head from 'next/head'
import 'tailwindcss/tailwind.css'
import Link from 'next/link';
import Sidebar from '../../components/admin/Sidebar'
import GenerationList from '../../components/admin/GenerationList'
import FrequencyColumn from '../../components/admin/FrequencyColumn'


export default function Frequency() {

  return (
    <div className="grid grid-cols-12 grid-flow-col gap-4 p-4 h-screen">
      <Sidebar active="technology"/>
      <div className="col-span-10 rounded-lg bg-gray-800 h-full p-4 antialiased text-white grid grid-cols-2">
        <div className=" col-span-1 p-2">
          <p className="text-white text-2xl text-center">Generaciones</p>
          <div className="w-100 h-100 rounded-lg bg-gray-700 p-4 mt-2 shadow-md">
            <Link href="/admin/frequency/add"><button className="rounded-lg bg-green-600 p-2 mb-4">Agregar generación</button></Link>
            <table className="table-auto w-full text-center">
              <thead>
                <tr>
                  <th className="font-semibold">ID</th>
                  <th className="font-semibold">Nombre</th>
                  <th className="font-semibold">Acciones</th>
                </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
          </div>
        </div>
        <FrequencyColumn />
      </div>
    </div>
  )
}

// src/routes/admin/technology/index.svelte
<script>
import { variables } from '$lib/variables';
  import Row from '$lib/row.svelte';
  import { goto } from '$app/navigation';

  async function fetchData(){
    console.log("Mounted! Listing technologies");
    const res = await fetch(`${variables.apiEndpoint}/technology`);
    const data = await res.json();

    if (res.ok) {
      console.log(data);
      return data;
    } else {
      throw new Error(data);
    }
  }

  let promise = fetchData();

  async function handleDelete(event){
    console.log("HANDLING DELETE!");
    console.log(event.detail);
    const res = await fetch(`${variables.apiEndpoint}/technology/${event.detail.id}`, {
      method: 'DELETE'
    })
    console.log(res);
    if (res.status != 200) {
      console.log("ERROR DELETING");
    } else {
      console.log("ALL OK");
      promise = await fetchData();
    }
  }
</script>
<main>
  <h1 class="text-center">Tecnologías</h1>
  <div class="w-100 h-100 rounded-lg bg-gray-700 p-4 mt-2 shadow-md">
    <a href="/admin/technology/add"><button class="rounded-lg bg-green-600 p-2 mb-4">Agregar Tecnología</button></a>
    {#await promise}
      <p>Cargando...</p>
    {:then items}
      <table class="table-auto w-full text-center">
        <thead>
          <tr>
            <th class="font-semibold">ID</th>
            <th class="font-semibold">Nombre</th>
            <th class="font-semibold">Status</th>
            <th class="font-semibold">Acciones</th>
          <tr>
        </thead>
        <tbody>
        {#each items.technologies as technology}
          <Row name={technology.name} id={technology.id} enabled={technology.enabled} url="technology" on:message={handleDelete}/>
        {/each}
        </tbody>
      </table>
    {:catch error}
      <p class="text-red-600">{error.message}</p>
    {/await}
  </div>

</main>
